import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ComponentSelector } from "../../node_modules/@emotion/serialize/dist/declarations/types/index.d";
import Navbar from "@/components/nav_components/Navbar";
import Hero from "@/components/nav_components/Hero";
import { Box } from "@mui/material";
import Footer_index from "@/components/footer/Footer_index";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prestmit Tech Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box className="bg-blue py-6 bg-no-repeat bg-right-top  bg-[url(https://prestmit-tech-test.s3.eu-west-1.amazonaws.com/Ellipse+9.png)] " sx={{backgroundSize:'40%'}}>
        
        <Navbar/>
        <Hero/>
       
        </Box>
        {children} 
        <Footer_index />
      </body>
    </html>
  );
}
